before_script:
  - sudo gem install fastlane
  - cd Boomerang

stages:
  - release
  - beta

build_project:
  stage: release
  script:
    - fastlane beta
  only: master
  
  build_project:
  stage: release
  script:
    - fastlane beta
  only: master