before_script:
  - sudo gem install fastlane
  - cd Boomerang

stages:
  - deploy

deploy_beta:
  stage: deploy
  script:
    - fastlane beta
  only:
    - dev

deploy_production:
  stage: deploy
  script:
    - fastlane release
  only:
    - master