before_script:  
  - cd Boomerang

stages:
  - deploy

deploy_alpha:
  stage: deploy
  script:
    - fastlane alpha
  only:
    - dev
  tags:
    - ios10

deploy_beta:
  stage: deploy
  script:
    - fastlane beta
  only:
    - test
  tags:
    - ios10

deploy_production:
  stage: deploy
  script:
    - fastlane release
  only:
    - master
  tags:
    - ios10
