# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :ios

app_base_bundle = "lab262.boomerang"


  platform :ios do
    
    before_all do
      ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/'
      ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
      ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "hhdv-tiws-qlmu-dvzc"
      cocoapods
    end

    desc "Submit a new Alpha Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :alpha do
      app_final_bundle = app_base_bundle + ".dev"
      match(type: "appstore", app_identifier: app_final_bundle) # more information: https://codesigning.guide
      increment_build_number_in_plist(
        build_number: "#{number_of_commits}",
        target: app_final_bundle
      )
      gym(scheme: app_final_bundle, include_bitcode: false, clean: true)
      changelog_from_git_commits # this will generate the changelog based on your last commits
      testflight(username: "thiago.mb@icloud.com",
      team_name:"Thiago Bernardes",
      beta_app_description: "Olá Futuros Boomers! Como estão?

      Pra quem não sabe, nós somos uma plataforma que tenta ajudar a repensar nossa maneira de consumir, diminuindo gastos supérfluos através do aluguel e troca de produtos entre os membros da comunidade.


        Equipe Boomerang",
      beta_app_feedback_email: "tmb0710@gmail.com",
      skip_submission: false,
      skip_waiting_for_build_processing: false,
      distribute_external: true,
      changelog: "Novidades e melhorias de performance.",
      groups: "Internal",
      wait_processing_interval:1200)

      slack(message: 'Successfully distributed a new TestFlight ALPHA build')
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
      app_final_bundle = app_base_bundle + ".test"
      match(type: "appstore", app_identifier: app_final_bundle) # more information: https://codesigning.guide
      increment_build_number_in_plist(
        build_number: "#{number_of_commits}",
        target: app_final_bundle
      )
      gym(scheme: app_final_bundle, include_bitcode: false, clean: true)
      changelog_from_git_commits # this will generate the changelog based on your last commits
      testflight(username: "thiago.mb@icloud.com",
      team_name:"Thiago Bernardes",
      beta_app_description: "Olá Futuros Boomers! Como estão?

      Pra quem não sabe, nós somos uma plataforma que tenta ajudar a repensar nossa maneira de consumir, diminuindo gastos supérfluos através do aluguel e troca de produtos entre os membros da comunidade.


        Equipe Boomerang",
      beta_app_feedback_email: "tmb0710@gmail.com",
      skip_submission: false,
      skip_waiting_for_build_processing: false,
      distribute_external: true,
      changelog: "Novidades e melhorias de performance.",
      groups: "Internal",
      wait_processing_interval:1200)

      slack(message: 'Successfully distributed a new TestFlight BETA build')
    end

    desc "Deploy a new version to the App Store"
    lane :release do
      app_final_bundle = app_base_bundle + ".production"
      match(type: "appstore")
      increment_version_number_in_plist( # Set a specific version number
      version_number: "2.#{number_of_commits}",
      target: app_final_bundle
      )
      increment_version_number
      gym(scheme: app_final_bundle, include_bitcode: false, clean: true)
      deliver(username: "thiago.mb@icloud.com",team_name:"Thiago Bernardes",force: true,app_identifier:app_final_bundle)
      slack(message: 'Successfully released a new App Store build')
    end

    after_all do |lane|

    end

    error do |lane, exception|

    end
  end
