exclude:
    - '**Tests.swift'   # Ignore Swift files that end in "Tests"
    - Carthage   # Ignore Swift files under "Source/Carthage/"
    - Pods     # Ignore Swift files under "Source/Pods/"
    - Vendor      # Ignore Swift files under "Source/Pods/"
