# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# link_with 'Boomerang'

target 'Boomerang' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'SwiftyJSON'
    pod 'JSQMessagesViewController'
    pod 'Kingfisher', '~> 3.0'
    pod 'PHFComposeBarView', '~> 2.0.1'
   # Pods for Boomerang

  target 'BoomerangTests' do
    inherit! :search_paths
    # Pods for testing
  end







end
