# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# link_with 'Boomerang'


def common_pods
    inhibit_all_warnings!
    use_frameworks!

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Parse'
    pod 'ParseLiveQuery'
    pod 'ParseFacebookUtilsV4'
    pod 'SwiftyJSON'
    pod 'JSQMessagesViewController'
    pod 'Kingfisher', '~> 3.0'
    pod 'PHFComposeBarView', '~> 2.0.1'
    pod 'ImagePicker'

end

target 'lab262.boomerang.test' do
  common_pods
end

target 'lab262.boomerang.production' do
    common_pods
end

target 'lab262.boomerang.dev' do
    common_pods
end

target 'BoomerangTests' do
    inherit! :search_paths
    # Pods for testing
    common_pods
end
